<?php
// Generated by Zend Framework 2
return array(
    'BFolliot\ZfNl2br\Module'             => __DIR__ . '/Module.php',
    'BFolliot\ZfNl2br\Filter\Nl2brFilter' => __DIR__ . '/src/BFolliot/ZfNl2br/Filter/Nl2brFilter.php',
);